apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-git-files-plugin-read-secrets
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-git-files-plugin-read-secrets
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: {{ include "this.serviceAccountName" . }}
    namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-git-files-plugin-read-secrets
